include(CheckIncludeFiles)
include(CheckIncludeFileCXX)
include(CheckFunctionExists)
include(CheckCXXCompilerFlag)
include(CheckSymbolExists)
include(CheckCCompilerFlag)
include(FindPackageHandleStandardArgs)

if(CMAKE_COMPILER_IS_GNUCXX)
  if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS 8.1)
    message(FATAL_ERROR "GCC 8.1+ required due to C++17 requirements")
  endif()
endif()

check_symbol_exists(__func__ "" HAVE_FUNC)
if(HAVE_FUNC)
  add_definitions(-DHAVE_FUNC)
endif(HAVE_FUNC)
check_symbol_exists(__PRETTY_FUNCTION__ "" HAVE_PRETTY_FUNC)
if(HAVE_PRETTY_FUNC)
  add_definitions(-DHAVE_PRETTY_FUNC)
endif(HAVE_PRETTY_FUNC)

include(TestBigEndian)
test_big_endian(COMMON_BIG_ENDIAN)
if(COMMON_BIG_ENDIAN)
  add_definitions(-DCOMMON_BIG_ENDIAN)
endif(COMMON_BIG_ENDIAN)
